### ISSUE TITLE
Gimme-37: UI Prototype

### ISSUE THREAD

**Issue by NexRX** [NexRX/Gimme#37]
### Description:
To aid in development of Gimme. Some UI prototypes are required to be made in order to provide a straight forward path of what needs to be developed in the view. These are prototypes and therefore are heavily subject to change but should provide a solid guide and goal of waht to acheive.

### Criteria:
- [X] 1.  Initial home screens including splash screen.
- [x] 2.  Journey from _Home/Send Screen_ to _Send Complete Screen_ via the first 4 methods to implement for a release.
   - [x] 2a.  [Wireless Method](https://github.com/Nex-Coder/Gimme/issues/36)
   - [x] 2b.  Wired Method
   - [x] 2c.  Email Method
- [x] 3.  First Advance Source (GDrive - Subject to change)
   - [x]  3a. Journey via Wirelessly
   - [x]  3b. Journey via Wired
   - [x]  3c. Journey via Email
   - [x]  3d. Journey via first Advance Method (SSH/SFTP - Subject to change)
- [x] 4.  Journey from _Receive Screen_ to _Receive Complete Screen_
- [x] 5. Journey from Settings to Saved Settings

### Notes
This story won't be fully split into tasks so complete steps and check them off at will.

**Comment by Nex-Coder** [comment]
Modified the task list as some design decisions where made in some new prototyping work
